spring:
  application:
    name: mall-ware
  datasource:
    url: jdbc:mysql://192.168.25.51:3306/mall_wms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 只扫描自己工程的 mapper
  global-config:
    db-config:
      id-type: auto # 设置主键自增

server:
  port: 11000